config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'answers#new'
  resources :answers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/confirmed', to: "answers#confirmed"
  get '/infos', to:"pages#infos"
end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create, :confirmed]
  # , only: [:new]
  def index
    @answers = Answer.all
  end

  def show
  end

  def new
    @answer = Answer.new
  end

  def create
    @answer = Answer.new(answer_params)
    if @answer.save
      redirect_to confirmed_path
    else
      render 'new'
    end
  end

  def edit
    @answer = Answer.find(params[:id])
  end

  def update
    @answer = Answer.find(params[:id])
    if @answer.update(answer_params)
      redirect_to answers_path
    else
      render 'update'
    end
  end

  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy
    redirect_to answers_path
  end

  def confirmed
  end

  private

  def answer_params
    params.require(:answer).permit(:name, :present, :mairie, :absent, :number_of_invites, :comment, :invite1, :invite2, :invite3, :invite4, :invite5, :invite6)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :infos]

  def home
  end

  def infos
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/confirmed.html.erb
<div class="message-confirmation col-12">
  <%= image_tag("https://res.cloudinary.com/dnhdzmowt/image/upload/v1575033561/Ha%CC%82te_de_faire_la_fe%CC%82te_avec_vous_1_pifcbe.png") %>

</div>

app/views/answers/edit.html.erb
<div class="row pagesavedate">

  <div class="justify-content-center align-items-center col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
    <div class="confirmation-presence">

      <h5>
        Changer la réponse de <% @answer.name %> </h5>
        <br>


        <%= simple_form_for @answer do |f| %>
        <%= f.input :name, label: "Nom et Prénom : " %>

        <div class="row">
          <div class="col-sm">
            <%= f.input :present, label:"Oui, je serai présent(e) !", class: "checkbox", input_html: { id: "1" } %>
          </div>
          <div class="col-sm">
            <%= f.input :number_of_invites, default:0, label: "     | Nous serons : " , collection: [0, 1, 2, 3, 4, 5, 6, 7], input_html: {id: "4", :style=> 'width: 25%;', :rows => 4}%>
          </div>
        </div>


        <div class="row">
          <div class="col-sm">
            <div id="inviteenplus1">
              <%= f.input :invite1, label:"Invité 1 :" %>
            </div>

          </div>
          <div class="col-sm">
            <div id="inviteenplus2">
              <%= f.input :invite2, label:"Invité 2 :" %>
            </div>

          </div>
          <div class="col-sm">
            <div id="inviteenplus3">
              <%= f.input :invite3, label:"Invité 3 :" %>
            </div>

          </div>
        </div>

        <div class="row">
          <div class="col-sm">
            <div id="inviteenplus4">
              <%= f.input :invite4, label:"Invité 4 :" %>
            </div>

          </div>
          <div class="col-sm">
            <div id="inviteenplus5">
              <%= f.input :invite5, label:"Invité 5 :" %>
            </div>

          </div>
          <div class="col-sm">
            <div id="inviteenplus6">
              <%= f.input :invite6, label:"Invité 6 :" %>
            </div>

          </div>
        </div>



        <%= f.input :mairie, label:"Non, mais je serai présent(e) au mariage civil à Paris", class: "checkbox", input_html: { id: "2" }  %>
        <%= f.input :absent, label:"Je ne vais pas pouvoir mais je penserai à vous !", class: "checkbox", input_html: { id: "3" }  %>
        <%= f.input :comment, label: "Laissez nous un petit mot : ", :as => :text, input_html: { :style=> 'width: 100%;', :rows => 4} %>
        <%= f.submit "ENVOYER", class: 'btn btn-send' %>
        <% end %>


      </div>
    </div>
  </div>



  <script>

    const checkbox1 = document.getElementById("1");

    const checkbox2 = document.getElementById("2");

    const checkbox3 = document.getElementById("3");

    function handleChecked1() {

      checkbox2.checked = false;

      checkbox3.checked = false;

    }

    function handleChecked2() {

      checkbox1.checked = false;

      checkbox3.checked = false;

    }

    function handleChecked3() {

      checkbox1.checked = false;

      checkbox2.checked = false;

    }

    function unable() {
      if (checkbox2.checked) {
        document.getElementById("4").disabled = true;
      }
      else if (checkbox3.checked) {
        document.getElementById("4").disabled = true;
      }
      else {
        document.getElementById("4").disabled = false;
      }
    }


    checkbox1.addEventListener('change', handleChecked1)
    checkbox2.addEventListener('change', handleChecked2)
    checkbox3.addEventListener('change', handleChecked3)




  </script>

app/views/answers/index.html.erb
<%= link_to('Logout', destroy_user_session_path, class: "btn-send", method: :delete) %>
<% if current_user.admin %>
<div class="container">
  <h1>Ceux qui ont répondus
    <% a = 0 %>
    <% @answers.each do |answer|  %>
    <% a += answer.number_of_invites %>
    <% end %>
  </h1>
  <h2>Nombre d'invités : <%= a %></h2>


  <table class="table">
    <thead>
      <tr>
        <th scope="col">Nom</th>
        <th scope="col">👨‍👩‍👧‍👦</th>
        <th scope="col">🌲</th>
        <th scope="col">💒</th>
        <th scope="col">❌</th>
        <th scope="col">Petit mot 📋</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @answers.each do |answer| %>
      <tr>
        <th scope="row">
          <h5><strong> <%= answer.name %></strong> </h5>
          <div>
            <%= answer.invite1 %>
          </div>
          <div>
            <%= answer.invite2 %>
          </div>
          <div>
            <%= answer.invite3 %>
          </div>
          <div>
            <%= answer.invite4 %>
          </div>
          <div>
            <%= answer.invite5 %>
          </div>
          <div>
            <%= answer.invite6 %>
          </div>



        </th>
        <td><%= answer.number_of_invites %></td>
        <td><%= answer.present ? "🌲" : "-" %></td>
        <td><%= answer.mairie ? "💒" : "-" %></td>
        <td><%= answer.absent ? "❌" : "-" %></td>
        <td><%= answer.comment %></td>
        <td>
        </td>
        <td><%= link_to "Edit", edit_answer_path(answer)%> <span>|</span>
          <%= link_to "Delete", answer_path(answer),
          method: :delete,
          data: { confirm: "Are you sure?" }, class:"btn-del" %> </td>
        </tr>
        <%end%>
      </tbody>
    </table>



  </div>
  <% end %>

app/views/answers/new.html.erb
<div class="row pagesavedate">
  <div class="savedate col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
    <%= image_tag("https://res.cloudinary.com/dnhdzmowt/image/upload/v1574985452/Frame_30-3_p001_w3dqhq.jpg") %>

  </div>
  <div class="justify-content-center align-items-center col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
    <div class="confirmation-presence">

      <h5>
      Confirmation de votre présence : </h5>
      <br>


      <%= simple_form_for @answer do |f| %>
      <%= f.input :name, label: "Nom et Prénom : " %>

      <div class="row">
        <div class="col-sm">
          <%= f.input :present, label:"Oui, je serai présent(e) !", class: "checkbox", input_html: { id: "1" } %>
        </div>
        <div class="col-sm">
          <%= f.input :number_of_invites, default:0, label: "     | Nous serons : " , collection: [0, 1, 2, 3, 4, 5, 6, 7], input_html: {id: "4", :style=> 'width: 25%;', :rows => 4}%>
        </div>
      </div>


      <div class="row">
        <div class="col-sm">
          <div id="inviteenplus1" style="display: none">
            <%= f.input :invite1, label:"Invité 2 :" %>
          </div>

        </div>
        <div class="col-sm">
          <div id="inviteenplus2" style="display: none">
            <%= f.input :invite2, label:"Invité 3 :" %>
          </div>

        </div>
        <div class="col-sm">
          <div id="inviteenplus3" style="display: none">
            <%= f.input :invite3, label:"Invité 4 :" %>
          </div>

        </div>
      </div>

      <div class="row">
        <div class="col-sm">
          <div id="inviteenplus4" style="display: none">
            <%= f.input :invite4, label:"Invité 5 :" %>
          </div>

        </div>
        <div class="col-sm">
          <div id="inviteenplus5" style="display: none">
            <%= f.input :invite5, label:"Invité 6 :" %>
          </div>

        </div>
        <div class="col-sm">
          <div id="inviteenplus6" style="display: none">
            <%= f.input :invite6, label:"Invité 7 :" %>
          </div>

        </div>
      </div>



      <%= f.input :mairie, label:"Non, mais je serai présent(e) au mariage civil à Paris", class: "checkbox", input_html: { id: "2" }  %>
      <%= f.input :absent, label:"Je ne vais pas pouvoir mais je penserai à vous !", class: "checkbox", input_html: { id: "3" }  %>
      <%= f.input :comment, label: "Laissez nous un petit mot : ", :as => :text, input_html: { :style=> 'width: 100%;', :rows => 4} %>
      <%= f.submit "ENVOYER", class: 'btn btn-send' %>
      <% end %>


    </div>
  </div>
</div>



<script>

  const checkbox1 = document.getElementById("1");

  const checkbox2 = document.getElementById("2");

  const checkbox3 = document.getElementById("3");

  function handleChecked1() {

    checkbox2.checked = false;

    checkbox3.checked = false;

  }

  function handleChecked2() {

    checkbox1.checked = false;

    checkbox3.checked = false;

  }

  function handleChecked3() {

    checkbox1.checked = false;

    checkbox2.checked = false;

  }

  function unable() {
    if (checkbox2.checked) {
      document.getElementById("4").disabled = true;
    }
    else if (checkbox3.checked) {
      document.getElementById("4").disabled = true;
    }
    else {
      document.getElementById("4").disabled = false;
    }
  }


  checkbox1.addEventListener('change', handleChecked1)
  checkbox2.addEventListener('change', handleChecked2)
  checkbox3.addEventListener('change', handleChecked3)

  constnum = document.getElementById("4")
  constnum.addEventListener('change', (event)=> {
    let i = 1;
    const num = constnum.value;
    while (i<=6) {
      let element = document.getElementById(`inviteenplus${i}`);
      if (i < num) {
        console.log(element);

        element.style.display = "block";
      } else {
        element.style.display = "none";
      }
      i+=1;
    }

  })


</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="icon" href="  https://as1.ftcdn.net/jpg/01/41/84/62/500_F_141846275_XS9U5If2t8fMyjXPwvkjD4pdqchOiPV6.jpg" />

  <title>Giulia et Tristan</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
</head>
<body>
  <%#= render 'shared/navbar' %>
  <%= render 'shared/flashes' %>
  <%= yield %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/infos.html.erb
<div class="row scroll text-center">
  <div class="savedate col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
    <%= cl_image_tag("https://res.cloudinary.com/dnhdzmowt/image/upload/v1584103736/templett_1_nhrs4w.png") %>
  </div>
  <div class="savedate col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">

    <%= cl_image_tag("https://res.cloudinary.com/dnhdzmowt/image/upload/v1584103736/templett_2_tr4jrt.png") %>

  </div>
  <div class="savedate col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">

    <%= link_to "https://www.paypal.com/pools/c/8nglNf5kYV" do  %>
    <%= cl_image_tag("https://res.cloudinary.com/dnhdzmowt/image/upload/v1584105007/giuliaa_jtzic2.png") %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>